### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by lnguyen** [genevieve/leftovers#146]
Is it possible to cut new release with new assume role arn feature?

**Comment by genevieve** [comment]
Hey @lnguyen - I can cut a release but I haven't been able to test any of the latest changes since the prior release on any IAAS due to a current lack of credentials/accounts for testing. If you (or others who find this) find any bugs, please open issues/MRs where you can.

**Comment by genevieve** [comment]
I've cut v0.70.0 as a pre-release for now

**Comment by lnguyen** [comment]
thanks!!
