### ISSUE TITLE
vSphere VM deletion output is weird

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#18]
```
Deleting bbl-concourse-worker.
SUCCESS deleting !
```

**Comment by genevieve** [comment]
I think this is an old version of leftovers because the format of the output recently changed: https://github.com/genevieve/leftovers/blob/master/vsphere/leftovers.go#L52-L61

Do you know what version of leftovers that is in bbl? I can bump again in case it has been a while.

**Comment by rowanjacobs** [comment]
It's probably fine in the actual latest version of bbl. Closing because I'm not going to go through the trouble of creating a VM on vSphere just to test this out.

**Comment by genevieve** [comment]
LOL k.
