### ISSUE TITLE
Filter resources by type

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#20]
It would be cool to be able to run `leftovers --filter ${env-name} --type forwarding-rule` or somesuch and *only* blow away forwarding rules. It would be very cool to be able to run `leftovers --filter ${env-name} --skip-type tag` or somesuch to get around, for instance, AWS tagging weirdness.

**Comment by genevieve** [comment]
- [ ] Each resource with List has a Type function

- [ ] Each iaas leftovers has a `DeleteTypes` function that only lists and deletes for those types that match the `--types` inputs

**Comment by genevieve** [comment]
Alright Rowan! This is now ready. 😆 (Now that you've rolled off the team!)

**Comment by rowanjacobs** [comment]
And not a moment too soon!
