### ISSUE TITLE
Use Terraform provider variables for credentials

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#32]
Currently, we only read credentials out of environment variables used by [bbl](https://github.com/cloudfoundry/bosh-bootloader). The [AWS](https://www.terraform.io/docs/providers/aws/#environment-variables), [GCP](https://www.terraform.io/docs/providers/google/#configuration-reference), and [vSphere](https://www.terraform.io/docs/providers/vsphere/#argument-reference) Terraform providers support the use of environment variables for authentication. As a courtesy to users who are cleaning up after Terraform rather than `bbl`, we could allow using those environment variables to authenticate.

**Comment by genevieve** [comment]
I was thinking about that! The go-flags library doesn't support more than one environment variable. Do you know of any other libraries?

**Comment by rowanjacobs** [comment]
Although there certainly are a wide variety of go flag parsing libraries, I'm not aware of any that will let you do this. We may have to write our own.

**Comment by rowanjacobs** [comment]
(Actually I think [viper](https://github.com/spf13/viper) might but it's pretty heavyweight. We could probably PR [jhanda](https://github.com/pivotal-cf/jhanda) to have multiple environment variable support.)

**Comment by genevieve** [comment]
https://github.com/pivotal-cf/jhanda/issues/3

**Comment by rowanjacobs** [comment]
(Blocked by pivotal-cf/jhanda#4)

**Comment by genevieve** [comment]
Decided switching to jhanda might be a lot of work since there isn't a lot of investment in making the global usage like what we have with go-flags now.

Added support for the main env vars that terraform supports for each provider and that should help (mostly removing the `BBL_` prefix makes it easier for non-bbl users to understand.)
