### ISSUE TITLE
Godoc link?

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#40]
Since this can be used as a library, maybe we should have a godoc link on the readme. (And maybe some godocs.)

**Comment by genevieve** [comment]
If you add it to vsphere or something, I can mimic it for the other IaaSes.

**Comment by rowanjacobs** [comment]
I would just add docs to the basic deletable interfaces and maybe not to each individual resource type.

**Comment by rowanjacobs** [comment]
Scratch that, I might add one line of documentation to the resource type itself that explains what IaaS resource it corresponds to.

**Comment by rowanjacobs** [comment]
I've documented Azure and vSphere resource types (so like.... only 3 out of the billion supported by this app) because they're a bit subtle or tricky. I think we could just stick to documenting resource types that aren't 100% self-explanatory.

**Comment by genevieve** [comment]
Yeah, I think the ones you did for vsphere are good since that one is more nuanced.

**Comment by genevieve** [comment]
@rowanjacobs Are you cool if I close this issue and we can continue to keep up docs when new iaas' are added? (I think openstack and nsxt deletion is up next.)

**Comment by rowanjacobs** [comment]
Yep!
