### ISSUE TITLE
Clean up NSX-T resources

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#41]
I may write something to clean up NSX-T resources (in particular the ones created by terraforming-vsphere) if I have time.

**Comment by genevieve** [comment]
This looks like the list of resources that can be created/deleted from the terraform provider for nsx-t! All yours :-) https://github.com/genevieve/leftovers/blob/master/RESOURCES.md#vmware-nsx-t

**Comment by genevieve** [comment]
If you want, we can close this issue now that you've started on nsx-t resources, and open separate issues for different resources you need to destroy?

**Comment by rowanjacobs** [comment]
Done! Enjoy your 13 new nearly identical GitHub issues!
