### ISSUE TITLE
Delete NSX-T ns services

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#45]
The following Terraform resource types should be automatically cleaned up by leftovers:
- [algorithm type ns service](https://www.terraform.io/docs/providers/nsxt/r/algorithm_type_ns_service.html)
- [ether type ns service](https://www.terraform.io/docs/providers/nsxt/r/ether_type_ns_service.html)
- [icmp type ns service](https://www.terraform.io/docs/providers/nsxt/r/icmp_type_ns_service.html)
- [igmp type ns service](https://www.terraform.io/docs/providers/nsxt/r/igmp_type_ns_service.html)
- [ip protocol ns service](https://www.terraform.io/docs/providers/nsxt/r/ip_protocol_ns_service.html)
- [l4 port set ns service](https://www.terraform.io/docs/providers/nsxt/r/l4_port_set_ns_service.html)

**Comment by genevieve** [comment]
API guide is here: https://www.vmware.com/support/nsxt/doc/nsxt_22_api.html

**Comment by rowanjacobs** [comment]
[VMware documentation on NS services](https://docs.vmware.com/en/VMware-NSX-T/2.2/com.vmware.nsxt.admin.doc/GUID-B6AA9E5C-AD23-4629-8272-09C2EB686A77.html)

**Comment by genevieve** [comment]
ns services can be generically deleted so we thankfully do not have to do individual resources for each type of ns service! Should be out in the next release.
