### ISSUE TITLE
Delete NSX-T VM tags

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#46]
[NSX-T VM tags](https://www.terraform.io/docs/providers/nsxt/r/vm_tags.html) should be cleaned up by leftovers.

**Comment by rowanjacobs** [comment]
[VMware documentation on VM tags](https://docs.vmware.com/en/VMware-NSX-T/2.2/com.vmware.nsxt.admin.doc/GUID-020B7FA3-5A5F-47A2-B25E-9B331B0F26CC.html)

**Comment by genevieve** [comment]
Tags are deleted when a VM is deleted so I am going to close this issue.
