### ISSUE TITLE
Delete NSX-T NAT rules.

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#48]
Leftovers should clean up [NSX-T NAT rules](https://www.terraform.io/docs/providers/nsxt/r/nat_rule.html).

**Comment by rowanjacobs** [comment]
[VMware documentation on NSX-T NAT rules](https://docs.vmware.com/en/VMware-NSX-T/2.2/com.vmware.nsxt.admin.doc/GUID-E9B40B40-D0C4-4CC9-9706-E9C153FF1A6C.html)

**Comment by genevieve** [comment]
@rowanjacobs Is it possible that since NAT rules are created for a specific tier 1 router, that if you are deleting the router, you are deleting its NAT rules? Can you imagine a case where you would want to delete the NAT rules and not the router its on?

**Comment by genevieve** [comment]
It seems like you cannot have NAT rules independent of a router given the id is required when you create one with terraform: https://www.terraform.io/docs/providers/nsxt/r/nat_rule.html

**Comment by genevieve** [comment]
(Offline discussion that this story is not relevant since nat rules are not independent of routers and thus not deletable alone.)
