### ISSUE TITLE
leftovers falsely reports success deleting GCP network

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#5]
In trying to delete a particular network on GCP using leftovers:

```
leftovers --filter lite
Are you sure you want to delete network bbl-lite-gcp-network? (y/N): y
Deleting bbl-lite-gcp-network.
SUCCESS deleting bbl-lite-gcp-network!
```

But the network still exists, and must be deleted in the GCP console.

**Comment by genevieve** [comment]
I think this is when there are resources within it that have not been deleted. The next time it happens, check if there's a subnet still attached.

The gcp compute operation shows DONE and that's the success value we return but maybe there's special logic in what DONE means to them.

**Comment by genevieve** [comment]
```
Are you sure you want to delete subnetwork leftovers-test-subnet (Network:.../networks/leftovers-test)? (y/N): n
Are you sure you want to delete network leftovers-test? (y/N): y
Deleting leftovers-test.

SUCCESS deleting leftovers-test!
```

**Comment by genevieve** [comment]
So, the error does not get returned from the requests against the operation. The operation is returned with errors on that object. Now we do a check for errors from the operation and return it and it works! (Well, it errors correctly telling you that the resource/network is in use.)

https://github.com/genevieve/leftovers/commit/e3eca91a587259a88c18c96ce024a716f8fcd529

Thanks Rowan for opening the issue!
