### ISSUE TITLE
Delete NSX-T logical router link ports

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#50]
Leftovers should delete NSX-T logical router link ports on the [tier 0](https://www.terraform.io/docs/providers/nsxt/r/logical_router_link_port_on_tier0.html) and [tier 1](https://www.terraform.io/docs/providers/nsxt/r/logical_router_link_port_on_tier1.html) routers.

(Check if we already do this? Setting `force=true` on deletion of a tier 1 router deletes some ports, but I don't know which exact types of link ports are contained in this.)

**Comment by rowanjacobs** [comment]
[VMware documentation on tier 0/tier 1 logical router link ports](https://docs.vmware.com/en/VMware-NSX-T/2.2/com.vmware.nsxt.admin.doc/GUID-FEBB7758-8450-4176-92BA-4BDF3DB71181.html)

**Comment by genevieve** [comment]
[Equivalent delete command in terraform-provider-nsxt](https://github.com/terraform-providers/terraform-provider-nsxt/blob/234eeb0e29fa87ae9709876e096137a42c69b6b3/nsxt/resource_nsxt_logical_router_link_port_on_tier0.go#L149)

**Comment by genevieve** [comment]
https://www.vmware.com/support/nsxt/doc/nsxt_20_api.html#Methods.DeleteLogicalRouter

> Delete a Logical Router
> Deletes the specified logical router. You must delete associated logical router ports before you can delete a logical router. Otherwise use force delete which will delete all related ports and other entities associated with that LR. To force delete logical router pass force=true in query param.

To answer your question - yes deleting the router with `force=true` will delete the ports.
