### ISSUE TITLE
Delete NSX-T logical ports

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#51]
Leftovers should delete [NSX-T logical ports](https://www.terraform.io/docs/providers/nsxt/r/logical_port.html).

(distinct from NSX-T logical router link ports, these ports are attached to logical switches rather than logical routers and as such we don't clean them up in the tier 1 router cleanup code.)

**Comment by rowanjacobs** [comment]
[VMware documentation on logical switch ports](https://docs.vmware.com/en/VMware-NSX-T/2.2/com.vmware.nsxt.admin.doc/GUID-EC6E75A6-0F6C-4C34-82E5-E3899E680420.html)

**Comment by genevieve** [comment]
[Equivalent delete command in terraform-provider-nsxt](https://github.com/terraform-providers/terraform-provider-nsxt/blob/234eeb0e29fa87ae9709876e096137a42c69b6b3/nsxt/resource_nsxt_logical_port.go#L161)

**Comment by genevieve** [comment]
Use `cascade=true` to delete logical switch ports when deleting logical switches.

https://www.vmware.com/support/nsxt/doc/nsxt_20_api.html#Methods.DeleteLogicalSwitch

>Delete a Logical Switch
>Removes a logical switch from the associated overlay or VLAN transport zone. By default, a logical switch cannot be deleted if there are logical ports on the switch, or it is added to a NSGroup. Cascade option can be used to delete all ports and the logical switch. Detach option can be used to delete the logical switch forcibly.

**Comment by genevieve** [comment]
This will be covered by #52.
