### ISSUE TITLE
Delete NSX-T logical switches

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#52]
Leftovers should delete [NSX-T logical switches](https://www.terraform.io/docs/providers/nsxt/r/logical_switch.html).

**Comment by genevieve** [comment]
[Equivalent delete command in terraform-provider-nsxt](https://github.com/terraform-providers/terraform-provider-nsxt/blob/234eeb0e29fa87ae9709876e096137a42c69b6b3/nsxt/resource_nsxt_logical_switch.go#L292)

**Comment by genevieve** [comment]
https://github.com/genevieve/leftovers/issues/51#issuecomment-518346306

**Comment by genevieve** [comment]
For now, will only delete resources created by github.com/pivotal/paving

Gonna close this.
