### ISSUE TITLE
Delete NSX-T firewall sections

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#54]
Leftovers should delete [NSX-T firewall sections](https://www.terraform.io/docs/providers/nsxt/r/firewall_section.html).

**Comment by genevieve** [comment]
[Equivalent delete command in terraform-provider-nsxt](https://github.com/terraform-providers/terraform-provider-nsxt/blob/234eeb0e29fa87ae9709876e096137a42c69b6b3/nsxt/resource_nsxt_firewall_section.go#L411)

**Comment by genevieve** [comment]
For now, will only delete resources created by github.com/pivotal/paving

Gonna close this.
