### ISSUE TITLE
tilde expansion fails on macosx

### ISSUE THREAD

**Issue by markstokan** [genevieve/leftovers#57]
Quality of life improvement request :)

it would be nice to be able to run...
```
→ leftovers --filter aleppo-staging -i gcp --dry-run --gcp-service-account-key=~/Downloads/PCF-Toolsmiths-Dev-1-438abb4f0a12.json


Unmarshalling account key for project id: invalid character '~' looking for beginning of value
```

instead of the fully qualified path...
```
→ leftovers --filter aleppo-staging -i gcp --dry-run --gcp-service-account-key=/Users/pivotal/Downloads/PCF-Toolsmiths-Dev-1-438abb4f0a12.json
```

**Comment by genevieve** [comment]
Hey Mark! 

Could you try with `--gcp-service-account-key ~/Downloads/PCF-Toolsmiths-Dev-1-438abb4f0a12.json` without the `=`?

For some reason, leftovers does expand using `filepath.Abs(key)` but when the argument is passed in with `=`, it can't get the correct path. 

Not sure if this has somethibg to do with it: https://github.com/golang/go/issues/4140

**Comment by genevieve** [comment]
Actually, going to try this https://github.com/mitchellh/go-homedir
