### ISSUE TITLE
Exit 1 when leftovers fails to delete a resource

### ISSUE THREAD

**Issue by genevieve** [genevieve/leftovers#59]
Instead of just logging a warning, exit 1 with all errors.

- [x] GCP
- [x] Azure
- [x] AWS
- [x] NSX-T
- [x] vSphere

**Comment by genevieve** [comment]
[Fixed on GCP](https://github.com/genevieve/leftovers/commit/aa8fec87c41f89cb5b54416ca964050e492d86e7#commitcomment-30110050)

**Comment by rszumlakowski** [comment]
This reduces the teardown time in half because we don't have to run `leftovers --dry-run` after the initial call to see if anything was left behind. The first run will fail and tell us what's remaining.
