### ISSUE TITLE
OpenStack support

### ISSUE THREAD

**Issue by rszumlakowski** [genevieve/leftovers#69]
Hello Leftovers friends!

Are there any plans to add support to Leftovers for cleaning up environments on OpenStack?

**Comment by genevieve** [comment]
@rowanjacobs is very excited to add openstack support.

**Comment by rowanjacobs** [comment]
What OpenStack resources in particular are you looking to clean up? Ports have been our major problem when cleaning up environments manually or after failed `terraform destroy`, so I was thinking of prioritizing that first, but Terraform can create a lot more resources than that.

**Comment by rszumlakowski** [comment]
I'll be honest; I'm not sure exactly what would need to be cleaned up yet.  I'm very early in the planning stages for an environment paving tool that would eventually need to encapsulate OpenStack paves.  We currently use Leftovers to clean up on AWS, Azure, and GCP.  We're doing vSphere NSX-T next and OpenStack is planned for sometime after that.  This issue is mostly here to find out if you were planning on support OpenStack at some point and it sounds like the answer is "definitely maybe!"

**Comment by genevieve** [comment]
I added in the wiring for an openstack leftovers object and the first resource: floatingips v2. Let me know if that helps y'all get started on adding resources as you need to delete them! Also reach out if you want to xtm pair or open up separate github issues as you discover resources you want leftovers to delete :-)
