### ISSUE TITLE
GCP default route delete???

### ISSUE THREAD

**Issue by jbogie-pivotal** [genevieve/leftovers#71]
Should these really be showing up as an option to delete? If I remember correctly they are protected GCP resources.

Jakes-Work-MacBook-Pro:gcp-pksv1 jbogie$ leftovers
[Route: default-route-06fc87370b5a2adf] Delete? (y/N): y <--- Of course I had to try!

[Route: default-route-06fc87370b5a2adf] Deleting...
[Route: default-route-06fc87370b5a2adf] Delete: Do request: googleapi: Error 400: The local route cannot be deleted., badRequest

Suppress them from showing up unless a flag is thrown to enable them?!?

**Comment by jbogie-pivotal** [comment]
genevieve/tap/leftovers v0.44.0 already installed

**Comment by genevieve** [comment]
Hey @jbogie-pivotal! Sorry for the delay on this. I recently merged a PR for this functionality but didn't review it for any default checks/skips it should be doing for gcp route resources. Do you want to PR a fix, otherwise I can look into it later this week!

**Comment by genevieve** [comment]
Copying the commit body here: 

>  - These are system generated routes when you create a network. These
will be deleted by the deletion of the network and do not block the
deletion of that network.
> - There are no properties on the Route struct that indicate a route is a
default one. Typically, the name will contain the word "default" or the
description will contain the word "Default" but a property like Kind
returns "compute#route" for all routes.
> - Why delete routes then? In the case that a user has created a custom
route, they would not be able to delete the network that route belongs
to with leftovers while that route exists.

**Comment by genevieve** [comment]
Released in `v0.45.0`
