### ISSUE TITLE
Allow skipping delete orphaned EBS volumes on AWS

### ISSUE THREAD

**Issue by rowanjacobs** [genevieve/leftovers#79]
Running [kubernetes conformance tests](https://github.com/cncf/k8s-conformance) against PKS on AWS can leave EBS volumes temporarily unattached, since some of the conformance tests test attaching and detaching storage. As a result, teams that run those tests can't safely use leftovers in pipelines to clean up AWS environments, since it might interrupt the tests. To get around this, I suggest an option to skip volume deletion. The interface for this might look like `--skip-resource-type volume`.

**Comment by genevieve** [comment]
@rowanjacobs Do you know if the volumes they create are using `tags`?  Right now, for volumes, we assume that if they are `available` and _not_ `in-use`, then we can delete them. If more volumes were created with `tags`, then we would be able to do a check [in here](https://github.com/genevieve/leftovers/blob/aece12de8d99817bee13d35480d1c9a1c782a259/aws/ec2/volumes.go#L41-L46). I defaulted to the more common case where volumes are heavily orphaned _and_ don't use tags so most folks want them to be deleted. Unfortunately, volumes are commonly not tagged, and there are scenarios where volumes are detached but they shouldn't be deleted yet.

**Comment by rowanjacobs** [comment]
I have no idea if they tag volumes, and no idea how to find out myself (would this be an AWS CPI thing? something k8s-specific?). I think you may have to ask the PKS Releng team directly (or I can do so).

Another way to implement this would be to have a more general `--skip-resource-type` kind of flag. That's obviously a bigger story but could sidestep some of the PKS and AWS specific issues.

**Comment by genevieve** [comment]
Yeah, I think the `skip-resource-type` flag makes a lot of sense and aligns with this issue: https://github.com/genevieve/leftovers/issues/68

**Comment by genevieve** [comment]
I think I'm going to close this issue with the release of v0.52.0 and @xtreme-jon-ji's PR #88. We are going to require the filter match some string in the volume's name/tags. For users who want to clean up orphaned bosh volumes that don't have the environment name in them - I think they can do a separate run and search for the word `bosh-stemcell`. This might be the safest way to ensure users don't accidentally delete volumes they need.
