### ISSUE TITLE
GCP - Delete Cloud Routers

### ISSUE THREAD

**Issue by jbogie-pivotal** [genevieve/leftovers#82]
It appears that leftovers is not picking up the 'Cloud Routers' in the 'Hybrid Connectivity' section of GCP.

The 'terraforming-gcp' project creates a cloud router for the Control-Plane instance of ATC for Concourse.

**Comment by jbogie-pivotal** [comment]
Add `cloud-routers` as a new object type that leftovers can enumerate.

**Comment by genevieve** [comment]
Oh yay, new resources to delete! @nmahoney-pivotal @Polar-Beard is this something y’all would be interested in adding?
