### ISSUE TITLE
--type application option being ignored when combined with --dry-run

### ISSUE THREAD

**Issue by jbogie-pivotal** [genevieve/leftovers#92]
When performing the following:

`leftovers -d -t ec2-key-pair`

I receive the same output as doing:

`leftovers -d`

The order of the application options does not matter...same result either way.

I would expect that if I were to combine the two I would get a dry run output of only EC2 Key Pairs.

**Comment by genevieve** [comment]
Should be fixed in the latest release! Let me know if you discover anything!
