### ISSUE TITLE
Don't delete the GCP "Default Service Account"

### ISSUE THREAD

**Issue by mjj209** [genevieve/leftovers#93]
I don't have any data that shows people will actually do this, but experimentally, I found that if you run:

`leftovers -i gcp --gcp-service-account-key ~/Downloads/cf-sandbox-mjarvis-2b97fc3f60b5.json`

i.e. don't provide a filter

Then it will ask you:
`[IAM Service Account: projects/cf-sandbox-mjarvis/serviceAccounts/904156999061-compute@developer.gserviceaccount.com] Delete? (y/N):`
The answer is **NO**! But if you press yes, you're in for a world of hurt. Toolsmiths recently started validating this account exists before we let you deploy a GCP environment, and we documented the [process to recover](http://pivotal.github.io/cf-toolsmiths-docs/pivotal-cf-experimental/toolsmiths-envs/known-issues/) the account.

It could be useful to prevent users from deleting this account, as well as some of the other special GCP accounts, I've provided the list of accounts _I believe_ are special & shouldn't be deleted.

`[project-name]@appspot.gserviceaccount.com`
`[project-number]-compute@developer.gserviceaccount.com`

**Comment by anEXPer** [comment]
I've definitely accidentally deleted this account. I've done it personally at least once, and my team has done it independent of me at least once. It's a pain.

**Comment by genevieve** [comment]
Should be out in the next release! Thank you for determining what are the most likely default service account email structures.
