### ISSUE TITLE
Move leftovers pipelines to.. somewhere?

### ISSUE THREAD

**Issue by genevieve** [genevieve/leftovers#98]

**Comment by rowanjacobs** [comment]
Hush-house is a pretty good option. We can set up a hush-house team that admits either of our GitHub users (I think? can you do this in Concourse?) as authentication.

**Comment by genevieve** [comment]
Ouuu gotta get access to that.

**Comment by genevieve** [comment]
Put in a request.

**Comment by rowanjacobs** [comment]
The other nice thing about being on hush-house is that we don't need to have our own concourse workers for vSphere/OpenStack cluster access. The Toolsmiths external hush-house workers are basically team-agnostic; anyone can use them.

**Comment by genevieve** [comment]
Sweet. Closing this and moving to 🤐

**Comment by genevieve** [comment]
Done for reals now. 
https://github.com/cloudfoundry/infrastructure-ci/commit/a6bd105b7596ec9bb5234a2d279054760799ae71
